[package]
description = "12-column responsive Grid system, virtualized DataGrid (1M rows), and Bootstrap-style UI components in Rust Wasm."
name = "ferrox-front-ui"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/AI-Autistic-Intelligence/ferrox-front"
homepage = "https://ferrox-front.dev"
documentation = "https://docs.ferrox-front.dev"

[dependencies]
ferrox-front-core = { path = "../ferrox-front-core", version = "0.1.0" }


